<?php
$module = strtolower(\think\facade\Request::module());
$controller = strtolower(\think\facade\Request::controller());
$action = strtolower(\think\facade\Request::action());
?>
<!DOCTYPE html>
<html>
<head>
    <title>{$title} - <?php echo \app\base\model\Setting::instance()->getValue('site_name') ?></title>
    <meta name="Keywords" content="<?php echo \app\base\model\Setting::instance()->getValue('site_keywords') ?>" />
    <meta name="Description" content="<?php echo \app\base\model\Setting::instance()->getValue('site_description') ?>" />
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" href="__STATIC__/favicon.ico" type="image/x-icon" />
</head>
<body class="{$module}-{$controller}-{$action}">