<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录 - <?php echo \app\base\model\Setting::instance()->getValue('sys_name') ?></title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="shortcut icon" href="__STATIC__/favicon.ico" type="image/x-icon" />
</head>
<body>
<div>
    <form method="post" action="/admin/login">
        <input value="登录" type="submit">
    </form>
</div>
<!-- 底部结束 -->
<script type="text/javascript">
    if (typeof sfinit == 'function') {
        sfinit();
    }
    <?php
    $messages = sfget_admin_tmp_messages();
    if(!empty($messages)) :
    foreach ($messages as $msg):
    ?>
    alert('<?php echo addslashes($msg['content']) ?>');
    <?php
    endforeach;
    endif;
    ?>
</script>
</html>